Repository zendframework/zend-servicemanager, pull requests merged in 2018-02, with the labels that each got.

#187 Replace container-interop with PSR-11 container interface
  benchmarks/BenchAsset/AbstractFactoryFoo.php
  benchmarks/BenchAsset/FactoryFoo.php
  composer.json
  composer.lock
  docs/book/configuring-the-service-manager.md
  docs/book/delegators.md
  docs/book/migration-v4.md
  docs/book/migration.md
  docs/book/psr-11.md
  docs/book/quick-start.md
  mkdocs.yml
  src/AbstractFactory/ConfigAbstractFactory.php
  src/AbstractFactory/ReflectionBasedAbstractFactory.php
  src/AbstractFactoryInterface.php
  src/AbstractPluginManager.php
  src/DelegatorFactoryInterface.php
  src/Exception/ExceptionInterface.php
  src/Exception/ServiceNotCreatedException.php
  src/Exception/ServiceNotFoundException.php
  src/Factory/AbstractFactoryInterface.php
  src/Factory/DelegatorFactoryInterface.php
  src/Factory/FactoryInterface.php
  src/Factory/InvokableFactory.php
  src/FactoryInterface.php
  src/Initializer/InitializerInterface.php
  src/InitializerInterface.php
  src/PluginManagerInterface.php
  src/Proxy/LazyServiceFactory.php
  src/ServiceLocatorInterface.php
  src/ServiceManager.php
  src/Tool/ConfigDumper.php
  src/Tool/FactoryCreator.php
  test/AbstractFactory/ReflectionBasedAbstractFactoryTest.php
  test/AbstractPluginManagerTest.php
  test/CommonServiceLocatorBehaviorsTrait.php
  test/Factory/InvokableFactoryTest.php
  test/Proxy/LazyServiceFactoryTest.php
  test/TestAsset/AbstractFactoryFoo.php
  test/TestAsset/CallTimesAbstractFactory.php
  test/TestAsset/FailingAbstractFactory.php
  test/TestAsset/FailingExceptionWithStringAsCodeFactory.php
  test/TestAsset/FailingFactory.php
  test/TestAsset/PassthroughDelegatorFactory.php
  test/TestAsset/PreDelegator.php
  test/TestAsset/SampleFactory.php
  test/TestAsset/SimpleAbstractFactory.php
  test/TestAsset/SimpleInitializer.php
  test/TestAsset/factories/ComplexDependencyObject.php
  test/TestAsset/factories/InvokableObject.php
  test/TestAsset/factories/SimpleDependencyObject.php
  test/Tool/ConfigDumperTest.php
Labels: BC Break, enhancement

#259 [v4-dev] Improvement - import internal functions
  src/Config.php
  src/Exception/ContainerModificationsNotAllowedException.php
  src/Exception/InvalidArgumentException.php
  src/ServiceManager.php
  test/CommonServiceLocatorBehaviorsTrait.php
  test/ServiceManagerTest.php
Labels: enhancement

#257 Fixed links to the documentation
  CHANGELOG.md
  README.md
Labels: documentation
